// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectMarvin.Data;

#nullable disable

namespace ProjectMarvin.Migrations.ApplicationDbContextLogDataMigrations
{
    [DbContext(typeof(ApplicationDbContextLogData))]
    [Migration("20240725103255_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");
#pragma warning restore 612, 618
        }
    }
}
